export const ErrorCodes = {
  BOOK_NOT_FOUND: "BOOK_NOT_FOUND",
  BOOK_ALREADY_EXISTS: "BOOK_ALREADY_EXISTS",

  AUTHOR_NOT_FOUND: "AUTHOR_NOT_FOUND",

  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",

  USER_NOT_FOUND: "USER_NOT_FOUND",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  BOOK_UNAVAILABLE: "BOOK_UNAVAILABLE",

  VALIDATION_ERROR: "VALIDATION_ERROR",

  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
